# Generated by Django 3.2.9 on 2021-11-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='FirstName',
            new_name='Password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='LastName',
        ),
        migrations.AlterField(
            model_name='user',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
    ]
